# Use an official Python runtime as a base image
FROM python:3.9-slim     



# Set the working directory inside the container
WORKDIR /app




# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt




COPY main.py .
COPY final_model.pkl .



# Expose the FastAPI app port (default 8000)
EXPOSE 8000




# Run the FastAPI app with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
